<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0" xmlns:html="http://www.w3.org/1999/xhtml" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1" xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
  <xsl:template match="/">
    <html xmlns="http://www.w3.org/1999/xhtml">
      <head>
        <title>XML Sitemap - Genexlyf</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <style type="text/css">
          body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif;
            color: #333;
            max-width: 1200px;
            margin: 0 auto;
            padding: 20px;
            background-color: #f5f5f5;
          }
          h1 {
            color: #0EA5E9;
            border-bottom: 3px solid #0EA5E9;
            padding-bottom: 10px;
          }
          .intro {
            background-color: #fff;
            padding: 20px;
            margin: 20px 0;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
          }
          table {
            width: 100%;
            border-collapse: collapse;
            background-color: #fff;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
            border-radius: 8px;
            overflow: hidden;
          }
          th {
            background-color: #0EA5E9;
            color: #fff;
            text-align: left;
            padding: 12px;
            font-weight: 600;
          }
          td {
            padding: 12px;
            border-bottom: 1px solid #eee;
          }
          tr:hover {
            background-color: #f8f9fa;
          }
          a {
            color: #0EA5E9;
            text-decoration: none;
          }
          a:hover {
            text-decoration: underline;
          }
          .priority-high {
            color: #10b981;
            font-weight: 600;
          }
          .priority-medium {
            color: #f59e0b;
            font-weight: 600;
          }
          .priority-low {
            color: #6b7280;
          }
          .footer {
            margin-top: 30px;
            text-align: center;
            color: #6b7280;
            font-size: 14px;
          }
        </style>
      </head>
      <body>
        <h1>XML Sitemap</h1>
        <div class="intro">
          <p>This is an XML Sitemap, used by search engines like Google, Bing, and others to discover pages on your site.</p>
          <p><strong>Number of URLs:</strong> <xsl:value-of select="count(sitemap:urlset/sitemap:url)"/></p>
        </div>
        <table>
          <tr>
            <th>URL</th>
            <th>Last Modified</th>
            <th>Change Frequency</th>
            <th>Priority</th>
          </tr>
          <xsl:for-each select="sitemap:urlset/sitemap:url">
            <tr>
              <td>
                <xsl:variable name="itemURL">
                  <xsl:value-of select="sitemap:loc"/>
                </xsl:variable>
                <a href="{$itemURL}">
                  <xsl:value-of select="sitemap:loc"/>
                </a>
              </td>
              <td>
                <xsl:value-of select="sitemap:lastmod"/>
              </td>
              <td>
                <xsl:value-of select="sitemap:changefreq"/>
              </td>
              <td>
                <xsl:variable name="priority" select="sitemap:priority"/>
                <xsl:choose>
                  <xsl:when test="$priority &gt;= 0.9">
                    <span class="priority-high">
                      <xsl:value-of select="sitemap:priority"/>
                    </span>
                  </xsl:when>
                  <xsl:when test="$priority &gt;= 0.7">
                    <span class="priority-medium">
                      <xsl:value-of select="sitemap:priority"/>
                    </span>
                  </xsl:when>
                  <xsl:otherwise>
                    <span class="priority-low">
                      <xsl:value-of select="sitemap:priority"/>
                    </span>
                  </xsl:otherwise>
                </xsl:choose>
              </td>
            </tr>
          </xsl:for-each>
        </table>
        <div class="footer">
          <p>Generated by Genexlyf | <a href="https://genexlyf.com">Visit Website</a></p>
        </div>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet>

